INSERT INTO `Permiso`(`IdPermiso`, `ClavePermiso`, `DescripcionPermiso`, `CreatedAt`, `UpdatedAt`, `DeletedAt`, `CreatedBy`, `UpdatedBy`) VALUES
(23, "academicos-listar", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),
(24, "academicos-crear", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),
(25, "academicos-leer", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),
(26, "academicos-editar", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),
(27, "academicos-eliminar", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),

INSERT INTO `role_permiso`(`IdRole`, `IdPermiso`, `CreatedAt`, `UpdatedAt`, `DeletedAt`, `CreatedBy`, `UpdatedBy`) VALUES
(1, 23, current_timestamp, current_timestamp, null, 1, 1),
(1, 24, current_timestamp, current_timestamp, null, 1, 1),
(1, 25, current_timestamp, current_timestamp, null, 1, 1),
(1, 26, current_timestamp, current_timestamp, null, 1, 1),
(1, 27, current_timestamp, current_timestamp, null, 1, 1),



INSERT INTO `Permiso`(`IdPermiso`, `ClavePermiso`, `DescripcionPermiso`, `CreatedAt`, `UpdatedAt`, `DeletedAt`, `CreatedBy`, `UpdatedBy`) VALUES
(1, "academias-listar", "academias-listar", current_timestamp, current_timestamp, null, 1, 1),
(2, "academias-crear", "academias-listar", current_timestamp, current_timestamp, null, 1, 1),
(3, "academias-leer", "academias-listar", current_timestamp, current_timestamp, null, 1, 1),
(4, "academias-editar", "academias-listar", current_timestamp, current_timestamp, null, 1, 1),
(5, "academias-eliminar", "academias-listar", current_timestamp, current_timestamp, null, 1, 1),
(6, "academia-academico-crear", "academias-listar", current_timestamp, current_timestamp, null, 1, 1),
(7, "academia-academico-eliminar", "academias-listar", current_timestamp, current_timestamp, null, 1, 1),
(8, "sedes-listar", "sedes-listar", current_timestamp, current_timestamp, null, 1, 1),
(9, "sedes-crear", "sedes-listar", current_timestamp, current_timestamp, null, 1, 1),
(10, "sedes-leer", "sedes-listar", current_timestamp, current_timestamp, null, 1, 1),
(11, "sedes-editar", "sedes-listar", current_timestamp, current_timestamp, null, 1, 1),
(12, "sedes-eliminar", "sedes-listar", current_timestamp, current_timestamp, null, 1, 1),
(13, "facultades-listar", "facultades-listar", current_timestamp, current_timestamp, null, 1, 1),
(14, "facultades-crear", "facultades-listar", current_timestamp, current_timestamp, null, 1, 1),
(15, "facultades-leer", "facultades-listar", current_timestamp, current_timestamp, null, 1, 1),
(16, "facultades-editar", "facultades-listar", current_timestamp, current_timestamp, null, 1, 1),
(17, "facultades-eliminar", "facultades-listar", current_timestamp, current_timestamp, null, 1, 1),
(18, "tipoorganizador-listar", "tipoorganizador-listar", current_timestamp, current_timestamp, null, 1, 1),
(19, "tipoorganizador-crear", "tipoorganizador-listar", current_timestamp, current_timestamp, null, 1, 1),
(20, "tipoorganizador-leer", "tipoorganizador-listar", current_timestamp, current_timestamp, null, 1, 1),
(21, "tipoorganizador-editar", "tipoorganizador-listar", current_timestamp, current_timestamp, null, 1, 1),
(22, "tipoorganizador-eliminar", "tipoorganizador-listar", current_timestamp, current_timestamp, null, 1, 1),
(23, "academicos-listar", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),
(24, "academicos-crear", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),
(25, "academicos-leer", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),
(26, "academicos-editar", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),
(27, "academicos-eliminar", "academicos-listar", current_timestamp, current_timestamp, null, 1, 1),

INSERT INTO `role_permiso`(`IdRole`, `IdPermiso`, `CreatedAt`, `UpdatedAt`, `DeletedAt`, `CreatedBy`, `UpdatedBy`) VALUES
(1, 1, current_timestamp, current_timestamp, null, 1, 1),
(1, 2, current_timestamp, current_timestamp, null, 1, 1),
(1, 3, current_timestamp, current_timestamp, null, 1, 1),
(1, 4, current_timestamp, current_timestamp, null, 1, 1),
(1, 5, current_timestamp, current_timestamp, null, 1, 1),
(1, 6, current_timestamp, current_timestamp, null, 1, 1),
(1, 7, current_timestamp, current_timestamp, null, 1, 1),
(1, 8, current_timestamp, current_timestamp, null, 1, 1),
(1, 9, current_timestamp, current_timestamp, null, 1, 1),
(1, 10, current_timestamp, current_timestamp, null, 1, 1),
(1, 11, current_timestamp, current_timestamp, null, 1, 1),
(1, 12, current_timestamp, current_timestamp, null, 1, 1),
(1, 13, current_timestamp, current_timestamp, null, 1, 1),
(1, 14, current_timestamp, current_timestamp, null, 1, 1),
(1, 15, current_timestamp, current_timestamp, null, 1, 1),
(1, 16, current_timestamp, current_timestamp, null, 1, 1),
(1, 17, current_timestamp, current_timestamp, null, 1, 1),
(1, 18, current_timestamp, current_timestamp, null, 1, 1),
(1, 19, current_timestamp, current_timestamp, null, 1, 1),
(1, 20, current_timestamp, current_timestamp, null, 1, 1),
(1, 21, current_timestamp, current_timestamp, null, 1, 1),
(1, 22, current_timestamp, current_timestamp, null, 1, 1),
(1, 23, current_timestamp, current_timestamp, null, 1, 1),
(1, 24, current_timestamp, current_timestamp, null, 1, 1),
(1, 25, current_timestamp, current_timestamp, null, 1, 1),
(1, 26, current_timestamp, current_timestamp, null, 1, 1),
(1, 27, current_timestamp, current_timestamp, null, 1, 1),
